name: NakornpingQ
services:
  frontend:
    container_name: nakornpingq-frontend
    build: .
    ports:
      - ${NGINX_PORT}:5173
    networks:
      - nakornpingq-net
    environment:
      - NGINX_PROXY=${NGINX_PROXY}
      - NGINX_PORT=${NGINX_PORT}
networks:
  nakornpingq-net: # Check by using `docker network ls` command
    external: true